In [1]:
import numpy as np
from src.NN import*
from src.activation import*

In [2]:
# input data ( X ) with 3 samples(batch size ) and 4 features(inputs) per sample  - shape(3,4)
X = np.matrix([ [-0.05693121,  0.02699044, -0.04668455, -0.14169061],
                   [ 0.08689635,  0.02768719, -0.09711046,  0.03148172],
                    [ 0.08215857,  0.00052926,  0.08005648,  0.00782602]]   )
layer1 = Dense_layer(4,6)
layer2 = Dense_layer(6,3)
layer1.forward(X)
layer2.forward(layer1.output)
print(layer1.output)

[[-0.00555332  0.01396061  0.02083424  0.01501772 -0.00858531  0.01169559]
 [-0.0066448  -0.00961668  0.00013642 -0.02113864  0.01107102 -0.01011386]
 [ 0.00082726 -0.01326681 -0.02136112 -0.01485577  0.01916372 -0.00433848]]


In [3]:
X = np.matrix([ [-0.05693121,  0.02699044, -0.04668455, -0.14169061],
                   [ 0.08689635,  0.02768719, -0.09711046,  0.03148172],
                    [ 0.08215857,  0.00052926,  0.08005648,  0.00782602]]   )


    