In [ ]:
import numpy as np

In [ ]:
class Dense_layer:
    def __init__(self,n_inputs : int  , n_neurons : int ):
        self.weights = 0.1*np.random.randn(n_inputs , n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases
        return self.output


In [ ]:
# input data ( X ) with 3 samples(batch size ) and 4 features(inputs) per sample  - shape(3,4)
X = np.matrix([ [-0.05693121,  0.02699044, -0.04668455, -0.14169061],
                   [ 0.08689635,  0.02768719, -0.09711046,  0.03148172],
                    [ 0.08215857,  0.00052926,  0.08005648,  0.00782602]]   )
layer1 = Dense_layer(4,6)
layer2 = Dense_layer(6,3)
layer1.forward(X)
layer2.forward(layer1.output)
print(layer1.output)

[[ 0.0097579  -0.00557832  0.0180162  -0.01081713 -0.03154848  0.03204411]
 [-0.0140825  -0.00546603  0.00072923  0.00939759  0.03390055 -0.00191806]
 [-0.00698194 -0.00120286 -0.00585111  0.00184719  0.00824967 -0.00591315]]


(3, 5)
